export const CourseCate = [
  {
    id: 1,
    Cate: "School",
    link: "/courses/school",
    subCate: [
      {
        id: 1,
        course: "English speaking/Public speaking",
        banner: "https://www.baoiam.com/media/course_banners/Frame_2321.png",
        desc: [
          "Public speaking Welcome to the Public Speaking Mastery course, where students embark on an empowering journey to enhance their communication skills and build confidence. You will dive into the art of crafting compelling speeches, mastering effective delivery techniques, and engaging audiences with poise and clarity.",
          "Through interactive exercises, practice sessions, and constructive feedback, you'll learn how to present your ideas with impact and confidence. Whether you are preparing for a classroom presentation or a future career, this course will equip you with the essential skills to speak persuasively and connect with your audience effectively. Get ready to transform your public speaking abilities and discover the power of your voice!",
        ],
        overview: [
          "Public speaking course helps students overcome fear and anxiety associated with public speaking, fostering self-assurance in their abilities. It also teaches students how to structure and organize effective speeches and presentations.",
          "This program helps in improving students' vocal projection, body language, and engagement techniques to deliver impactful and persuasive speeches.",
          "Students are trained to understand and connect with their audience, tailoring their messages to different listeners and settings.",
        ],
        highlights: [
          "Live online classes - learn from our experts live",
          "Placement assistance - Access support for securing better jobs",
          "Internships get hands - on experience by working in several firms",
          "Letter of recommendation - enhance your credibility with endorsements from professionals",
          "Live projects - Hands on live project with expert guidance",
          "Doubt clearing sessions - get all your doubts cleared by your experts",
          "Placement assessment - get all your doubts cleared by your experts",
          "Certificate of completion - Evaluate your readiness for job opportunities",
          "Mentorship sessions - validated your skills with a recognized certification",
          "Digital resource hub - Guidance from industry experts",
        ],
        curriculum: [
          "1. Introduction to Public Speaking - Understanding Public Speaking",
          "2. Overcoming Nervousness Speech Structure and Content - Crafting Your Speech",
          "3. Developing Compelling Content Delivery Techniques - Voice and Articulation",
          "4. Body Language and Presence Engaging Your Audience - Connecting with Your Audience",
          "5. Interactive Speaking Speech Practice and Feedback Persuasive Speaking - Techniques for Persuasion",
          "6. Persuasive Speech Practice Advanced Presentation Skills - Using Visual Aids",
          "7. Managing Question and Answer Sessions Impromptu Speaking - Thinking on Your Feet",
          "8. Evaluating Impromptu Performances Speech Refinement",
        ],
        plans: [
          {
            id: 1,
            name: "Plus",
            courseName: "English speaking/Public speaking",
            price: 54999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "50+ Live projects & Internships",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
            ],
          },
          {
            id: 2,
            name: "Premium",
            courseName: "English speaking/Public speaking",
            price: 64999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
            ],
          },
          {
            id: 3,
            name: "Premium Combo",
            courseName: "English speaking/Public speaking",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "Interview preparation",
              "Resume building",
              "Network of top MNC industries & angels",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
        ],
      },
      {
        id: 2,
        course: "Creative writing",
        banner: "https://www.baoiam.com/media/course_banners/Frame_2314.png",
        desc: [
          "Creative writing is a type of writing that goes outside the bounds of normal professional, journalistic, academic, or technical forms of literature, typically identified by an emphasis on narrative craft, character development.",
          " It is used in literary tropes or with various traditions of poetry and poetics. Students will engage in writing exercises, workshops, and critiques to refine their craft and discover their unique voice.",
        ],
        overview: [
          "Creative writing course develops writing skills. It enhances students' ability to write compelling stories, poems, and essays. It will focus on exploring genres, improving writing technique, foster creativity, peer review, and finally review.",
          "This course encourages students to use their imagination and creativity to generate original ideas for stories, poems, and other forms of writing and experiment with different writing styles and genres to find their unique voice.",
          "Understand different writing techniques and styles used by authors to inspire their own writing with the help of creative writing course.",
          "This course helps in developing the skills to communicate ideas clearly and persuasively through written words. It also enhances the ability to critically evaluate and revise their own and others' writing.",
        ],
        highlights: [
          "Live online classes - learn from our experts live",
          "Placement assistance - Access support for securing better jobs",
          "Internships get hands - on experience by working in several firms",
          "Letter of recommendation - enhance your credibility with endorsements from professionals",
          "Live projects - Hands on live project with expert guidance",
          "Doubt clearing sessions - get all your doubts cleared by your experts",
          "Placement assessment - get all your doubts cleared by your experts",
          "Certificate of completion - Evaluate your readiness for job opportunities",
          "Mentorship sessions - validated your skills with a recognized certification",
          "Digital resource hub - Guidance from industry experts",
        ],
        curriculum: [
          "1. Introduction to Creative Writing - Overview of creative writing and its importance. Basic principles of storytelling and self-expression.",
          "2. Fiction Writing - Plot development and structure.Character creation and development. Dialogue and voice.",
          "3. Poetry - Poetic forms and structures. Use of imagery, metaphor, and simile. Exploring rhythm and sound in poetry.",
          "4. Creative Non-Fiction - Writing personal essays and memoirs.Techniques for crafting compelling narratives based on real events.",
          "5. Drama and Playwriting - Fundamentals of writing plays and scripts. Understanding dramatic structure and character interaction.",
          "6. Writing Workshops - Peer review and critique sessions.Collaborative writing exercises.",
          "7. Revision and Editing - Strategies for revising drafts.Focus on grammar, style, and coherence.",
        ],
        plans: [
          {
            id: 1,
            name: "Plus",
            courseName: "Creative writing",
            price: 54999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
            ],
          },
          {
            id: 2,
            name: "Premium",
            courseName: "Creative writing",
            price: 64999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 3,
            name: "Premium Combo",
            courseName: "Creative writing",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 4,
            name: "Premium Plus",
            courseName: "Creative writing",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
        ],
      },
      {
        id: 3,
        course: "Art and craft (DIY)",
        banner: "https://www.baoiam.com/media/course_banners/Frame_2313.png",
        desc: [
          "Art and Craft Welcome to the Art and Craft Exploration course, a vibrant and imaginative journey designed for students. You will dive into a world of creativity through hands-on projects and artistic experimentation. From mastering drawing and painting techniques to crafting unique textile and sculpture pieces, this course offers a diverse range of activities that will ignite your artistic passion and help you express yourself.",
          " With a focus on creativity, skill development, and personal expression, you will build confidence in your artistic abilities while exploring the endless possibilities of art and craft. Get ready to create, explore, and showcase your unique artistic talents!",
        ],
        overview: [
          "Art and Craft course provides students with opportunities to explore and express their creativity through various art forms and craft techniques.",
          "The fundamental skills and techniques in drawing, painting, and crafting, help the students to improve their proficiency and artistic abilities.",
          "Students are introduced to different art styles, mediums, and artists, broadening their understanding and appreciation of art.",
          "This course inspires creativity and motivates students to experiment with different materials and methods, encouraging original and imaginative thinking in their projects.",
          "Art and Craft course also enhances students' self-confidence through successful completion of art and craft projects, promoting a positive sense of accomplishment and personal growth.",
        ],
        highlights: [
          "Live online classes - learn from our experts live",
          "Placement assistance - Access support for securing better jobs",
          "Internships get hands - on experience by working in several firms",
          "Letter of recommendation - enhance your credibility with endorsements from professionals",
          "Live projects - Hands on live project with expert guidance",
          "Doubt clearing sessions - get all your doubts cleared by your experts",
          "Placement assessment - get all your doubts cleared by your experts",
          "Certificate of completion - Evaluate your readiness for job opportunities",
          "Mentorship sessions - validated your skills with a recognized certification",
          "Digital resource hub - Guidance from industry experts",
        ],
        curriculum: [
          "1. Introduction to Art and Craft - Exploring Art Creative Expression",
          "2. Drawing Techniques - Basic Drawing Skills Exploring Styles",
          "3. Painting Fundamentals",
          "4. Crafting Basics - Introduction to Crafting Paper Crafts",
          "5. Sculpture and 3D Art - Exploring Sculpture Mixed Media Projects",
          "6. Textile Art - Fabric and Textiles Textile Creations",
          "7. Artistic Presentation - Preparing for Display Art Exhibition Preparation",
        ],
        plans: [
          {
            id: 1,
            name: "Plus",
            courseName: "Art and craft (DIY)",
            price: 54999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
            ],
          },
          {
            id: 2,
            name: "Premium",
            courseName: "Art and craft (DIY)",
            price: 64999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 3,
            name: "Premium Combo",
            courseName: "Art and craft (DIY)",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 4,
            name: "Premium Plus",
            courseName: "Art and craft (DIY)",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
        ],
      },
      {
        id: 4,
        course: "Critical thinking & problem solving",
        banner: "https://www.baoiam.com/media/course_banners/Frame_2318.png",
        desc: [
          "Critical Thinking and Problem Solving Welcome to the Creative Thinking and Problem Solving course, an exciting journey designed for students. This course aims to ignite your imagination and sharpen your problem-solving skills through engaging activities and collaborative projects.",
          " You will explore innovative thinking techniques, tackle real-world challenges, and work together to create unique solutions. With a focus on creativity, teamwork, and critical thinking, you will gain the confidence and skills needed to approach any problem with fresh perspectives and inventive ideas. Get ready to unleash your creativity and become a master problem solver!",
        ],
        overview: [
          "Critical thinking and problem solving course encourages students to think imaginatively and explore various ways to approach and solve problems, fostering an environment where creative ideas can flourish.",
          "This course equips students with effective strategies and techniques to analyze and address complex challenges, enhancing their ability to find innovative solutions and also boost students' self-esteem in their creative and analytical abilities through successful problem-solving experiences and constructive feedback.",
          "Strengthen your teamwork and communication skills by engaging in group activities and projects, emphasizing the importance of working together to achieve common goals.",
          "Connect classroom learning with real-world applications in order to apply your creative and problem-solving skills to practical, everyday problems.",
        ],
        highlights: [
          "Live online classes - learn from our experts live",
          "Placement assistance - Access support for securing better jobs",
          "Internships get hands - on experience by working in several firms",
          "Letter of recommendation - enhance your credibility with endorsements from professionals",
          "Live projects - Hands on live project with expert guidance",
          "Doubt clearing sessions - get all your doubts cleared by your experts",
          "Placement assessment - get all your doubts cleared by your experts",
          "Certificate of completion - Evaluate your readiness for job opportunities",
          "Mentorship sessions - validated your skills with a recognized certification",
          "Digital resource hub - Guidance from industry experts",
        ],
        curriculum: [
          "1. Introduction to Creative Thinking - What is Creativity? Creative Mindsets",
          "2. Problem-Solving Strategies - Identifying Problems Brainstorming Solutions",
          "3. Applying Creativity - Creative Problem Solving Techniques Hands-On Creative Project",
          "4. Working Together - Team Dynamics Collaborative Problem-Solving",
          "5. Real-World Application - Analyzing Real-World Problems Developing Solutions",
          "6. Prototyping and Testing - Creating Prototypes Testing and Refining",
          "7. Presentation Skills - Effective Presentation Techniques Preparing for Presentations",
        ],
        plans: [
          {
            id: 1,
            name: "Plus",
            courseName: "Critical thinking & problem solving",
            price: 54999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
            ],
          },
          {
            id: 2,
            name: "Premium",
            courseName: "Critical thinking & problem solving",
            price: 64999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 3,
            name: "Premium Combo",
            courseName: "Critical thinking & problem solving",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 4,
            name: "Premium Plus",
            courseName: "Critical thinking & problem solving",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
        ],
      },
      {
        id: 5,
        course: "Life Skills",
        banner: "https://www.baoiam.com/media/course_banners/Frame_2329.png",
        desc: [
          "Life Skills Welcome to the Life Skills course that aims to equip you with essential skills for managing everyday challenges and building a successful future. Through interactive lessons and hands-on activities, you will learn valuable techniques in personal management, effective communication, financial literacy, health and wellness, safety, social etiquette, and digital literacy.",
          "By the end of this course, you will be better prepared to handle various situations confidently and responsibly, setting a strong foundation for your personal and academic growth. Let's embark on this journey to enhance your life skills and prepare for a bright future!",
        ],
        overview: [
          "Life skills are practical abilities and social competencies that help you navigate daily challenges and interactions. These skills include managing your time and finances, communicating clearly, understanding health and safety, and more.",
          "Life skills are crucial for your overall development and success. They help you become more independent, build strong relationships, make informed choices, and handle the various situations you encounter as you grow.",
          "This course helps in recognizing and mitigating risks associated with online activities and social media, identifying various career options and understanding the skills required for different professions, and understanding basic workplace expectations and professional behavior.",
          "Life skills course also helps to collaborate effectively in team settings and appreciate diverse perspectives, provide and receive constructive feedback to facilitate continuous improvement, and reflect on personal growth and the application of life skills in real-life scenarios.",
        ],
        highlights: [
          "Live online classes - learn from our experts live",
          "Placement assistance - Access support for securing better jobs",
          "Internships get hands - on experience by working in several firms",
          "Letter of recommendation - enhance your credibility with endorsements from professionals",
          "Live projects - Hands on live project with expert guidance",
          "Doubt clearing sessions - get all your doubts cleared by your experts",
          "Placement assessment - get all your doubts cleared by your experts",
          "Certificate of completion - Evaluate your readiness for job opportunities",
          "Mentorship sessions - validated your skills with a recognized certification",
          "Digital resource hub - Guidance from industry experts",
        ],
        curriculum: [
          "1. Personal Management - Time Management; Goal Setting; Organization",
          "2. Communication Skills - Verbal Communication; Non-Verbal Communication; Conflict Resolution",
          "3. Financial Literacy - Basic Money Management; Spending and Saving; Introduction to Banking",
          "4. Health and Wellness - Physical Health; Mental Health; Healthy Relationships",
          "5. Safety and First Aid - Personal Safety; First Aid Basics; Emergency Response",
          "6. Social Skills and Etiquette - Respect and Empathy; Table Manners and Social Etiquette; Teamwork and Cooperation",
          "7. Digital Literacy and Online Safety - Internet Safety; Digital Etiquette; Cyberbullying",
          "8. Career Exploration and Skills - Career Awareness; Skill Development; Workplace Basics",
        ],
        plans: [
          {
            id: 1,
            name: "Plus",
            courseName: "Life Skills",
            price: 54999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
            ],
          },
          {
            id: 2,
            name: "Premium",
            courseName: "Life Skills",
            price: 64999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 3,
            name: "Premium Combo",
            courseName: "Life Skills",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 4,
            name: "Premium Plus",
            courseName: "Life Skills",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
        ],
      },
      {
        id: 6,
        course: "Photography & editing skills",
        banner: "https://www.baoiam.com/media/course_banners/Frame_2310.png",
        desc: [
          "Photography and editing skills Photography is the art and practice of capturing an accurate picture with the help of a camera. It involves understanding how to use a camera with the percent angle, camera setting, such as shutter speed and ISO to control the exposure and composition of a photograph.",
          "Talking about photo editing is the process of enhancing an image using softwares. Editing allows photographers to adjust colors, contrast and sharpness and remove imperfection and add creative effects to the digital vision. Both skills enable you to not only capture the picture you see but also shape it according to what you want. Both skills are widely in demand in today's world.",
        ],
        overview: [
          "A photography and editing course provided a comprehensive introduction to the art of capturing and shaping images. It covers essential photography techniques, including camera settings, composition and lighting along with advanced methods like long exposure and macro photography.",
          "The course also delves into photo editing techniques, how to use different software to edit the picture perfect image and also how to apply creative tools in a picture.",
          "Throughout the course you will get practical knowledge and exercise of artistic deployment. This course equips you with the skills to create visually compelling photographs and edit them like a professional. So let's start together to master your photography and editing skills today by understanding the fundamentals of photography and knowing the cameras function in depth.",
          "By the end of this course you will gain confidence in your creative vision and powerful skills to edit emotions of any images with some mind blowing skills",
        ],
        highlights: [
          "Live online classes - learn from our experts live",
          "Placement assistance - Access support for securing better jobs",
          "Internships get hands - on experience by working in several firms",
          "Letter of recommendation - enhance your credibility with endorsements from professionals",
          "Live projects - Hands on live project with expert guidance",
          "Doubt clearing sessions - get all your doubts cleared by your experts",
          "Placement assessment - get all your doubts cleared by your experts",
          "Certificate of completion - Evaluate your readiness for job opportunities",
          "Mentorship sessions - validated your skills with a recognized certification",
          "Digital resource hub - Guidance from industry experts",
        ],
        curriculum: [
          "1. Skill development",
          "2. Basic camera skills and introduction to editing",
          "3. Creative expression with artistic exploration and project-based learning",
          "4. Visual storytelling and editing challenges",
          "5. Introduction to technology and safe online sharing",
          "6. Confidence building and teamwork collaboration",
        ],
        plans: [
          {
            id: 1,
            name: "Plus",
            courseName: "Photography & editing skills",
            price: 54999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
            ],
          },
          {
            id: 2,
            name: "Premium",
            courseName: "Photography & editing skills",
            price: 64999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 3,
            name: "Premium Combo",
            courseName: "Photography & editing skills",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 4,
            name: "Premium Plus",
            courseName: "Photography & editing skills",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
        ],
      },
      {
        id: 7,
        course: "Technology Development with AI and Coding",
        banner: "https://www.baoiam.com/media/course_banners/Frame_2326-1.png",
        desc: [
          "Technology Development with AI and Coding Course Introducing the course focused on Technology Development with AI and Coding to the students. It is crucial for a person in contemporary society with the abundance of various technological advancements to know and even more to possess the skills in artificial intelligence and coding basics.",
          "In this relation, the goals of this course include an understanding of skills and knowledge that will be effective as the student embarks on a future career in technology. Obtain general knowledge about the field of artificial intelligence like machine learning, neural networks, and data processing.",
        ],
        overview: [
          "Become armored with contemporary information in AI and coding, which prepares you for future technologies. Discover the basic knowledge one must acquire to take up different popular occupations in the sphere of IT.",
          "Dive into this course and learn the basics of Artificial Intelligence, coding languages, and programming.",
          "Earn the foundational knowledge of artificial intelligence, such as machine learning, neural networks, and data processing. Research how the implementation of AI in several domains affects individuals.",
          "Learn programming languages like Python, Java, and programming C++. Solve problems generically by use of coded exercises or projects.",
        ],
        highlights: [
          "Live online classes - learn from our experts live",
          "Placement assistance - Access support for securing better jobs",
          "Internships get hands - on experience by working in several firms",
          "Letter of recommendation - enhance your credibility with endorsements from professionals",
          "Live projects - Hands on live project with expert guidance",
          "Doubt clearing sessions - get all your doubts cleared by your experts",
          "Placement assessment - get all your doubts cleared by your experts",
          "Certificate of completion - Evaluate your readiness for job opportunities",
          "Mentorship sessions - validated your skills with a recognized certification",
          "Digital resource hub - Guidance from industry experts",
        ],
        curriculum: [
          "1. Introduction to Technology and Coding - Overview of technology trends and AI. Introduction to coding (basic concepts, algorithms)",
          "2. Basic Programming Concepts - Variables, data types, and control structures, Functions, loops, and conditionals",
          "3. Introduction to Python - Python basics (syntax, data structures) Hands-on Python exercises and mini-projects",
          "4. Data Handling and Analysis - Introduction to data handling (libraries like Pandas), Basic data analysis and visualization techniques",
          "5. Fundamentals of Artificial Intelligence - Overview of AI concepts (machine learning, neural networks), Introduction to AI tools and platforms (TensorFlow, Keras)",
          "6. Building AI Models - Training and testing AI models Hands-on project: Creating a simple AI model",
          "7. AI Applications and Ethics - Real-world AI applications (healthcare, finance, robotics), Discussing the ethical implications of AI",
          "8. Project Development - Project planning and development, Mid-project reviews and troubleshooting",
          "9. Final Projects and Presentations - Final project completion and preparation for presentations, Presentation of projects and course review",
        ],
        plans: [
          {
            id: 1,
            name: "Plus",
            courseName: "Technology Development with AI and Coding",
            price: 54999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
            ],
          },
          {
            id: 2,
            name: "Premium",
            courseName: "Technology Development with AI and Coding",
            price: 64999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 3,
            name: "Premium Combo",
            courseName: "Technology Development with AI and Coding",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
          {
            id: 4,
            name: "Premium Plus",
            courseName: "Technology Development with AI and Coding",
            price: 84999.0,
            courseItems: [
              "Live Classes",
              "Doubt clearing sessions",
              "Structured courses & PDFs",
              "Assessment & case study",
              "50+ Live projects & Internships",
              "5+ Internship Opportunities",
              "Mentorship",
              "Interview preparation",
              "Resume building",
              "Placement assistance",
              "Network of top MNC industries & angels",
              "investors",
              "Webinar and seminar access",
              "Placement Assessment",
              "Resource Hub",
              "Placement assistance",
            ],
          },
        ],
      },
      { id: 8, course: "Entrepreneurship & Innovation" },
      { id: 9, course: "Social Media and Digital Marketing" },
      { id: 10, course: "Finance" },
    ],
  },
  {
    id: 2,
    Cate: "College",
    link: "/courses/college",
    subCate: [
      { id: 10, course: "Web Development" },
      { id: 11, course: "Graphic Designing" },
      { id: 12, course: "Human Resource" },
      { id: 13, course: "Data Analytics" },
      { id: 14, course: "Product Management" },
      { id: 15, course: "Android Development" },
      { id: 16, course: "Digital Marketing" },
      { id: 17, course: "UI UX Design" },
      { id: 18, course: "Software Testing" },
      { id: 19, course: "Entrepreneurship and Innovation" },
    ],
  },
];

// Contact form
export const industry = [
  {
    id: 1,
    label: "Technology - Hardware",
    value: "Technology - Hardware",
  },
];

export const interestedCheckbox = [
  {
    id: 1,
    label: "Communication training",
    value: "Communication training",
  },
  {
    id: 2,
    label: "Conferences",
    value: "Conferences",
  },
  {
    id: 3,
    label: "Content collaboration",
    value: "Content collaboration",
  },
  {
    id: 4,
    label: "Custom events",
    value: "Custom events",
  },
  {
    id: 5,
    label: "Media",
    value: "Media",
  },
  {
    id: 6,
    label: "Podcasts",
    value: "Podcasts",
  },
  {
    id: 7,
    label: "Other (list below)",
    value: "other",
  },
];
